### ISSUE TITLE
Create model failed with server internal error

### ISSUE THREAD

**Issue by gggard** [RHEAGROUP/CDP4-IME-Community-Edition#448]
### Prerequisites

- [ X] I have written a descriptive issue title
- [ X] I have verified that I am running the latest version of the CDP4-IME
- [X ] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When I try to create a empty model, I got a exception from the server reported by the client.
I do not know if it is linked or not but the MMI does not permit to attach roles in the dedicated panel (I can not check boxes)

### Steps to Reproduce
Just create a new engineering model in the CDP client.

#### From the client (Logger CDP4EngineeringModel.ViewModels.EngineeringModelSetupDialogViewModel)
CDP4Dal.Exceptions.DalWriteException: The CDP4 Services replied with code InternalServerError: Internal Server Error: "exception:0A000: source for a multiple-column UPDATE item must be a sub-SELECT or ROW() expression"
   at CDP4ServicesDal.CdpServicesDal.<Write>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CDP4Dal.Session.<Write>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CDP4Composition.Mvvm.DialogViewModelBase`1.<ExecuteOkCommand>d__105.MoveNext()

#### From the server

2020-06-18 12:45:46.648 UTC [1] LOG: listening on IPv4 address "0.0.0.0", port 5432

2020-06-18 12:45:46.648 UTC [1] LOG: listening on IPv6 address "::", port 5432

2020-06-18 12:45:46.654 UTC [1] LOG: listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"

2020-06-18 12:45:46.685 UTC [72] LOG: database system was shut down at 2020-06-18 12:45:46 UTC

2020-06-18 12:45:46.693 UTC [1] LOG: database system is ready to accept connections

2020-06-18 12:49:26.968 UTC [79] ERROR: source for a multiple-column UPDATE item must be a sub-SELECT or ROW() expression at character 63

2020-06-18 12:49:26.968 UTC [79] STATEMENT: UPDATE "SiteDirectory"."Thing" SET ("ValueTypeDictionary") = ("ValueTypeDictionary" || $1) WHERE "Iid" = $2

2020-06-18 12:51:49.921 UTC [79] ERROR: source for a multiple-column UPDATE item must be a sub-SELECT or ROW() expression at character 63

2020-06-18 12:51:49.921 UTC [79] STATEMENT: UPDATE "SiteDirectory"."Thing" SET ("ValueTypeDictionary") = ("ValueTypeDictionary" || $1) WHERE "Iid" = $2

2020-06-18 12:57:25.507 UTC [79] ERROR: source for a multiple-column UPDATE item must be a sub-SELECT or ROW() expression at character 63

2020-06-18 12:57:25.507 UTC [79] STATEMENT: UPDATE "SiteDirectory"."Thing" SET ("ValueTypeDictionary") = ("ValueTypeDictionary" || $1) WHERE "Iid" = $2

2020-06-18 12:59:33.731 UTC [79] ERROR: source for a multiple-column UPDATE item must be a sub-SELECT or ROW() expression at character 103

2020-06-18 12:59:33.731 UTC [79] STATEMENT: UPDATE "EngineeringModel_0bae4e3f_7647_49a6_a891_2c36d17d0e6c"."Thing" SET ("ValueTypeDictionary") = ("ValueTypeDictionary" || $1) WHERE "Iid" = $2

### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 4.0.3.0
  - [ ] Other: 
  -
- Web Services:
  - [X ] CDP4 Web Services version: 4.0.0 (from Docker) 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): NA
  - [ X] Windows OS (32/64 bit): Win10
  - [ ] Additional information:

**Comment by samatrhea** [comment]
@gggard are you trying this on a locally hosted server or on a public server?

**Comment by gggard** [comment]
On a docker local server

**Comment by samatrhea** [comment]
i see you've mentioned the version of the CDP4 Server you are using, what version of the database docker are you using?

**Comment by gggard** [comment]
It came from the docker compose script, currently it is :
* rheagroup/cdp4-database-community-edition:latest (pull just 1h ago)
* rheagroup/cdp4-services-community-edition:4.0.0

**Comment by samatrhea** [comment]
ok, then, due to the fact that the latest postgres docker container is new for us we are a bit behind documentation. We are working on releasing a new docker build which should come this week or next. The solution to your issue is **not** use rheagroup/cdp4-database-community-edition:latest but tag *1.3.1*

**Comment by gggard** [comment]
Changed the version and drop the volumes and now it works, thanks for the reactivity ! 🥇 
I close the issue, I let you open it against the docker compose if needed
Thanks !

**Comment by alexatrhea** [comment]
@gggard the new compose files have indeed been released preemptively to work with services 6.0.0 which are currently in release candidate stage.

Two solutions indeed, as Sam mentioned using database 1.3.1 tag with services 4.0.0. Or using the release candidate option in (compose)[https://github.com/RHEAGROUP/CDP4-Docker-Compose] by running `compose.bat rc` which will use latest database with 6.0.0-rc1 services. The actual full docker compose file can be found here: https://github.com/RHEAGROUP/CDP4-Docker-Compose/blob/master/docker-compose-rc.yml

**Comment by samatrhea** [comment]
@gggard happy to be of assistance. We'll let you know when the latest versions are ready, performance is about to improve even more and we are working on making the migration between the different docker setups is a smooth as possible.

If you have more questions, give us a shout via this channel
