### ISSUE TITLE
Investigate errors when using the reports on a different model

### ISSUE THREAD

**Issue by cozminvelciu** [RHEAGROUP/CDP4-IME-Community-Edition#742]
### Description
* When trying to use the Mass budget summary and detailed mass budget on a different model (VMMO) I get am error "Invalid data member 'MainData'"
* When using the equipment list only 1 line "Spacecraft is visible"

**Comment by cozminvelciu** [comment]
The original error:
```
Column 'SystemName_2_MassMargin' does not belong to table .
   at System.Data.DataRow.GetDataColumn(String columnName)
   at System.Data.DataRow.get_Item(String columnName)
   at MyDataSource.CreateDataObject()
   at CDP4Reporting.ViewModels.ReportDesignerViewModel.GetDataSource()
   at CDP4Reporting.ViewModels.ReportDesignerViewModel.RebuildDataSource()
```
