### ISSUE TITLE
IME exception when applying category to element definition

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#760]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

on CEFO training server, in training model, added category equipment to element definition solar array using drag and drop. when dropping, crash of CDP4 occurred. not reproducible, and category was applied correctly (when opening model afterwards. exception report available.

### Steps to Reproduce

so far not reproducible

### Logs

  - [ ] There are no logs regarding the issue
  - [x] I have attached a log file or included the relevant section in this issue  
  
[CDP4 IME exception - add category to element definition on training model.txt](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/6070552/CDP4.IME.exception.-.add.category.to.element.definition.on.training.model.txt)

### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 7.0.1
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
From the logs:
```
CDP4ProductTree.ViewModels.ParameterOrOverrideBaseRowViewModel.<>c__DisplayClass37_0.<SetUsage>b__0(ParameterSubscription x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at CDP4ProductTree.ViewModels.ParameterOrOverrideBaseRowViewModel.SetUsage()
   at CDP4ProductTree.ViewModels.ParameterOrOverrideBaseRowViewModel.UpdateProperties()
```

it seems the product tree browser was open when this occured. We will have to see to reproduce. @MartinFijneman do you remember whether the ElementDefinition that you categorized contained ElementUsages with ParameterOverrides?

**Comment by MartinFijneman** [comment]
verified, quick check done, possible to drag-and-drop for Element Usage having paramater override.

since initial issue was not reproducible, consider this closed.

tested with:
CDP4-COMET version: 11.1.0 rc2
